<a href="https://colab.research.google.com/github/letsgooo123/Lab04web/blob/main/Numpy%EC%9D%98_%EA%B8%B0%EB%B3%B8_%EC%82%AC%EC%9A%A9%EB%B2%95(2025_03_10).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
List를 Numpy로 바꾸어 보기

import numpy as np

array = np.array([1, 2, 3])
print(array.size) # 배열의 크기
print(array.dtype) # 배열 원소의 타입
print(array[2]) # 인덱스 2의 원소

3
int64
3


In [3]:
Numpy 배열 합치기

import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
array3 = np.concatenate([array1, array2])

print(array3.shape)
print(array3)

(6,)
[1 2 3 4 5 6]


In [4]:
import numpy as np

array1 = np.arange(4).reshape(1, 4)
array2 = np.arange(8).reshape(2, 4)
array3 = np.concatenate([array1, array2], axis=0)

print(array3.shape)
print(array3)

(3, 4)
[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]


In [5]:
Numpy 배열 형태 바꾸기

import numpy as np

array1 = np.array([1, 2, 3, 4])
array2 = array1.reshape((2, 2))
print(array2.shape)

(2, 2)


In [6]:
Numpy 배열 나누기

import numpy as np

array = np.arange(8).reshape(2, 4)
left, right = np.split(array, [2], axis=1)

print(left.shape)
print(right.shape)
print(right[1][1])

(2, 2)
(2, 2)
7
